/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbnormalRouteImport } from './routes/abnormal'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as GoodsRouteImport } from './routes/goods'
import { Route as HandoverRouteImport } from './routes/handover'
import { Route as LanRouteImport } from './routes/lan'
import { Route as MailRouteImport } from './routes/mail'
import { Route as MoreRouteImport } from './routes/more'
import { Route as OtRouteImport } from './routes/ot'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShiftLogRouteImport } from './routes/shift-log'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ThreesRouteImport } from './routes/threes'
import { Route as UnfinishedRouteImport } from './routes/unfinished'
import { Route as AbnormalIndexRouteImport } from './routes/abnormal.index'
import { Route as AbnormalIdRouteImport } from './routes/abnormal.$id'
import { Route as GoodsIndexRouteImport } from './routes/goods.index'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as GoodsDataIdRouteImport } from './routes/goods.data.$id'
import { Route as GoodsExportIdRouteImport } from './routes/goods.export.$id'
import { Route as GoodsLotIdRouteImport } from './routes/goods.lot.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbnormalRoute = AbnormalRouteImport.update({
  id: '/abnormal',
  path: '/abnormal',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsRoute = GoodsRouteImport.update({
  id: '/goods',
  path: '/goods',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoverRoute = HandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => rootRouteImport,
} as any)
const LanRoute = LanRouteImport.update({
  id: '/lan',
  path: '/lan',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const OtRoute = OtRouteImport.update({
  id: '/ot',
  path: '/ot',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftLogRoute = ShiftLogRouteImport.update({
  id: '/shift-log',
  path: '/shift-log',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreesRoute = ThreesRouteImport.update({
  id: '/threes',
  path: '/threes',
  getParentRoute: () => rootRouteImport,
} as any)
const UnfinishedRoute = UnfinishedRouteImport.update({
  id: '/unfinished',
  path: '/unfinished',
  getParentRoute: () => rootRouteImport,
} as any)
const AbnormalIndexRoute = AbnormalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AbnormalRoute,
} as any)
const AbnormalIdRoute = AbnormalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AbnormalRoute,
} as any)
const GoodsIndexRoute = GoodsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GoodsRoute,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PeopleRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TasksRoute,
} as any)
const GoodsDataIdRoute = GoodsDataIdRouteImport.update({
  id: '/data/$id',
  path: '/data/$id',
  getParentRoute: () => GoodsRoute,
} as any)
const GoodsExportIdRoute = GoodsExportIdRouteImport.update({
  id: '/export/$id',
  path: '/export/$id',
  getParentRoute: () => GoodsRoute,
} as any)
const GoodsLotIdRoute = GoodsLotIdRouteImport.update({
  id: '/lot/$id',
  path: '/lot/$id',
  getParentRoute: () => GoodsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abnormal': typeof AbnormalRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/backup': typeof BackupRoute
  '/goods': typeof GoodsRouteWithChildren
  '/handover': typeof HandoverRoute
  '/lan': typeof LanRoute
  '/mail': typeof MailRoute
  '/more': typeof MoreRoute
  '/ot': typeof OtRoute
  '/people': typeof PeopleRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shift-log': typeof ShiftLogRoute
  '/tasks': typeof TasksRouteWithChildren
  '/threes': typeof ThreesRoute
  '/unfinished': typeof UnfinishedRoute
  '/abnormal/$id': typeof AbnormalIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/abnormal/': typeof AbnormalIndexRoute
  '/goods/': typeof GoodsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/goods/data/$id': typeof GoodsDataIdRoute
  '/goods/export/$id': typeof GoodsExportIdRoute
  '/goods/lot/$id': typeof GoodsLotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/backup': typeof BackupRoute
  '/handover': typeof HandoverRoute
  '/lan': typeof LanRoute
  '/mail': typeof MailRoute
  '/more': typeof MoreRoute
  '/ot': typeof OtRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shift-log': typeof ShiftLogRoute
  '/threes': typeof ThreesRoute
  '/unfinished': typeof UnfinishedRoute
  '/abnormal/$id': typeof AbnormalIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/abnormal': typeof AbnormalIndexRoute
  '/goods': typeof GoodsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/goods/data/$id': typeof GoodsDataIdRoute
  '/goods/export/$id': typeof GoodsExportIdRoute
  '/goods/lot/$id': typeof GoodsLotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abnormal': typeof AbnormalRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/backup': typeof BackupRoute
  '/goods': typeof GoodsRouteWithChildren
  '/handover': typeof HandoverRoute
  '/lan': typeof LanRoute
  '/mail': typeof MailRoute
  '/more': typeof MoreRoute
  '/ot': typeof OtRoute
  '/people': typeof PeopleRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shift-log': typeof ShiftLogRoute
  '/tasks': typeof TasksRouteWithChildren
  '/threes': typeof ThreesRoute
  '/unfinished': typeof UnfinishedRoute
  '/abnormal/$id': typeof AbnormalIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/abnormal/': typeof AbnormalIndexRoute
  '/goods/': typeof GoodsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/goods/data/$id': typeof GoodsDataIdRoute
  '/goods/export/$id': typeof GoodsExportIdRoute
  '/goods/lot/$id': typeof GoodsLotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abnormal'
    | '/attendance'
    | '/backup'
    | '/goods'
    | '/handover'
    | '/lan'
    | '/mail'
    | '/more'
    | '/ot'
    | '/people'
    | '/reports'
    | '/scan'
    | '/search'
    | '/settings'
    | '/shift-log'
    | '/tasks'
    | '/threes'
    | '/unfinished'
    | '/abnormal/$id'
    | '/people/$id'
    | '/tasks/$id'
    | '/abnormal/'
    | '/goods/'
    | '/people/'
    | '/tasks/'
    | '/goods/data/$id'
    | '/goods/export/$id'
    | '/goods/lot/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/backup'
    | '/handover'
    | '/lan'
    | '/mail'
    | '/more'
    | '/ot'
    | '/reports'
    | '/scan'
    | '/search'
    | '/settings'
    | '/shift-log'
    | '/threes'
    | '/unfinished'
    | '/abnormal/$id'
    | '/people/$id'
    | '/tasks/$id'
    | '/abnormal'
    | '/goods'
    | '/people'
    | '/tasks'
    | '/goods/data/$id'
    | '/goods/export/$id'
    | '/goods/lot/$id'
  id:
    | '__root__'
    | '/'
    | '/abnormal'
    | '/attendance'
    | '/backup'
    | '/goods'
    | '/handover'
    | '/lan'
    | '/mail'
    | '/more'
    | '/ot'
    | '/people'
    | '/reports'
    | '/scan'
    | '/search'
    | '/settings'
    | '/shift-log'
    | '/tasks'
    | '/threes'
    | '/unfinished'
    | '/abnormal/$id'
    | '/people/$id'
    | '/tasks/$id'
    | '/abnormal/'
    | '/goods/'
    | '/people/'
    | '/tasks/'
    | '/goods/data/$id'
    | '/goods/export/$id'
    | '/goods/lot/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbnormalRoute: typeof AbnormalRouteWithChildren
  AttendanceRoute: typeof AttendanceRoute
  BackupRoute: typeof BackupRoute
  GoodsRoute: typeof GoodsRouteWithChildren
  HandoverRoute: typeof HandoverRoute
  LanRoute: typeof LanRoute
  MailRoute: typeof MailRoute
  MoreRoute: typeof MoreRoute
  OtRoute: typeof OtRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShiftLogRoute: typeof ShiftLogRoute
  TasksRoute: typeof TasksRouteWithChildren
  ThreesRoute: typeof ThreesRoute
  UnfinishedRoute: typeof UnfinishedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abnormal': {
      id: '/abnormal'
      path: '/abnormal'
      fullPath: '/abnormal'
      preLoaderRoute: typeof AbnormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods': {
      id: '/goods'
      path: '/goods'
      fullPath: '/goods'
      preLoaderRoute: typeof GoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handover': {
      id: '/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof HandoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lan': {
      id: '/lan'
      path: '/lan'
      fullPath: '/lan'
      preLoaderRoute: typeof LanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ot': {
      id: '/ot'
      path: '/ot'
      fullPath: '/ot'
      preLoaderRoute: typeof OtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shift-log': {
      id: '/shift-log'
      path: '/shift-log'
      fullPath: '/shift-log'
      preLoaderRoute: typeof ShiftLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threes': {
      id: '/threes'
      path: '/threes'
      fullPath: '/threes'
      preLoaderRoute: typeof ThreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unfinished': {
      id: '/unfinished'
      path: '/unfinished'
      fullPath: '/unfinished'
      preLoaderRoute: typeof UnfinishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abnormal/': {
      id: '/abnormal/'
      path: '/'
      fullPath: '/abnormal/'
      preLoaderRoute: typeof AbnormalIndexRouteImport
      parentRoute: typeof AbnormalRoute
    }
    '/abnormal/$id': {
      id: '/abnormal/$id'
      path: '/$id'
      fullPath: '/abnormal/$id'
      preLoaderRoute: typeof AbnormalIdRouteImport
      parentRoute: typeof AbnormalRoute
    }
    '/goods/': {
      id: '/goods/'
      path: '/'
      fullPath: '/goods/'
      preLoaderRoute: typeof GoodsIndexRouteImport
      parentRoute: typeof GoodsRoute
    }
    '/people/': {
      id: '/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/goods/data/$id': {
      id: '/goods/data/$id'
      path: '/data/$id'
      fullPath: '/goods/data/$id'
      preLoaderRoute: typeof GoodsDataIdRouteImport
      parentRoute: typeof GoodsRoute
    }
    '/goods/export/$id': {
      id: '/goods/export/$id'
      path: '/export/$id'
      fullPath: '/goods/export/$id'
      preLoaderRoute: typeof GoodsExportIdRouteImport
      parentRoute: typeof GoodsRoute
    }
    '/goods/lot/$id': {
      id: '/goods/lot/$id'
      path: '/lot/$id'
      fullPath: '/goods/lot/$id'
      preLoaderRoute: typeof GoodsLotIdRouteImport
      parentRoute: typeof GoodsRoute
    }
  }
}

interface AbnormalRouteChildren {
  AbnormalIdRoute: typeof AbnormalIdRoute
  AbnormalIndexRoute: typeof AbnormalIndexRoute
}

const AbnormalRouteChildren: AbnormalRouteChildren = {
  AbnormalIdRoute: AbnormalIdRoute,
  AbnormalIndexRoute: AbnormalIndexRoute,
}

const AbnormalRouteWithChildren = AbnormalRoute._addFileChildren(
  AbnormalRouteChildren,
)

interface GoodsRouteChildren {
  GoodsIndexRoute: typeof GoodsIndexRoute
  GoodsDataIdRoute: typeof GoodsDataIdRoute
  GoodsExportIdRoute: typeof GoodsExportIdRoute
  GoodsLotIdRoute: typeof GoodsLotIdRoute
}

const GoodsRouteChildren: GoodsRouteChildren = {
  GoodsIndexRoute: GoodsIndexRoute,
  GoodsDataIdRoute: GoodsDataIdRoute,
  GoodsExportIdRoute: GoodsExportIdRoute,
  GoodsLotIdRoute: GoodsLotIdRoute,
}

const GoodsRouteWithChildren = GoodsRoute._addFileChildren(GoodsRouteChildren)

interface PeopleRouteChildren {
  PeopleIdRoute: typeof PeopleIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleIdRoute: PeopleIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

interface TasksRouteChildren {
  TasksIdRoute: typeof TasksIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksIdRoute: TasksIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbnormalRoute: AbnormalRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  BackupRoute: BackupRoute,
  GoodsRoute: GoodsRouteWithChildren,
  HandoverRoute: HandoverRoute,
  LanRoute: LanRoute,
  MailRoute: MailRoute,
  MoreRoute: MoreRoute,
  OtRoute: OtRoute,
  PeopleRoute: PeopleRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShiftLogRoute: ShiftLogRoute,
  TasksRoute: TasksRouteWithChildren,
  ThreesRoute: ThreesRoute,
  UnfinishedRoute: UnfinishedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
